language: node_js
sudo: required
node_js:
  - "node"
notifications:
  email: false
cache:
  directories:
    - node_modules
services:
  - mysql
script:
  - npm run coveralls
env:
  - IS_TRAVIS=true
before_install:
  - mysql -e 'CREATE DATABASE easel_test;'
